package tutorengine.catalog;

import java.util.Collection;
import java.util.TreeMap;
import tutorengine.model.Card;

// ============================================================================
// OWNER: Dimazana (Catalog & Priority). Karl is NOT in this file.
// Other members: do not edit this file.
// ============================================================================
// WHAT THIS IS: alphabetical card catalog. Key = Card name (case-insensitive),
// so inorder() prints the catalog A-Z for sheets and the UI.
//
// DO THIS (in order):
//  1. put/get/remove are done. get(missing) returns null - in main() print
//     "Not found: <name>" for that case (mirrors Karl's SKU search UX).
//  2. Extend main() demo with 5 REAL cards:
//     put 5 -> get 1 existing -> get 1 missing -> inorder print (must be A-Z)
//     -> remove 1 leaf -> remove the ROOT (first key) -> inorder again.
//  3. Deletion must work for leaf AND root (TreeMap handles it; show both).
//  4. TracePacket: 1 page - insert 5 keys step by step (tree shape), then
//     search hit + miss, then root deletion. Use real card names.
//  5. Live-change ready: instructor may say "delete the BST root" - practice
//     doing index.remove(index.firstKey()) live.
//
// ACCEPTANCE: inorder always A-Z; missing returns null+message; root delete works.
// DEFENSE Qs: O(log n) search/delete avg, O(n) worst; inorder/preorder/postorder?
//   (TreeMap gives inorder free; be ready to explain preorder/postorder order.)
// SPEC: S7 BST/Tree, S11 BST ops, Template H BST trace, T09.
// HOW TO TEST (OWNER: Dimazana):
//   RUN:  mvn -q exec:java -Dexec.mainClass=tutorengine.catalog.CatalogIndex
//   PASS WHEN DONE (put 5 real cards):
//     - get() of an existing name returns its card; get() of a missing name
//       prints "Not found: <name>" and returns null (no crash).
//     - inorder() prints all 5 names A-Z (case-insensitive).
//     - After removing one leaf AND the root (first key), inorder() still
//       prints the rest A-Z with nothing missing or duplicated.
// public class CatalogIndex {
    private final TreeMap<String, Card> index = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);

    public void put(Card c) { index.put(c.getName(), c); }
    public Card get(String name) { return index.get(name); }
    public Card remove(String name) { return index.remove(name); }
    public Collection<Card> inorder() { return index.values(); }
    public int size() { return index.size(); }

    public static void main(String[] args) {
        // TODO Dimazana: 5-card script from step 2. Print every step.
        System.out.println("CatalogIndex. OWNER: Dimazana. (implement 5-card demo)");
    }
}
