package tutorengine.priority;

import java.util.Comparator;
import java.util.PriorityQueue;
import tutorengine.model.Card;

// ============================================================================
// OWNER: Dimazana (Catalog & Priority). Karl is NOT in this file.
// Other members: do not edit this file.
// ============================================================================
// WHAT THIS IS: "Next to process" queue for the associate. Highest
// calculatePriority() card comes out first (max-heap via reversed comparator).
//
// FORMULA (keep + justify in report S4, 2+ attributes required):
//   (price*0.50) + (demandScore*0.35) - (quantity*3.0) + (foil ? 10 : 0)
// High price/demand rank up; overstock ranks down; foil +10 (curl protection).
//
// DO THIS (in order):
//  1. offer/peek/poll are done. Extend main() demo with 5 REAL cards including
//     1 obvious top (e.g. Mana Drain 2600/98/qty1) and 1 bulk (Llanowar 25/qty48).
//  2. Show: peek() = Mana Drain; poll() removes it; next peek() = runner-up.
//  3. Show a NEW highest card jumping the queue: offer an even hotter card last,
//     peek() must change to it.
//  4. Live-change ready: practice swapping the comparator (e.g. double the foil
//     bonus) and re-heapifying, since the instructor may ask "change weights".
//  5. TracePacket: 1 page - offer 3 cards (sift-up steps) + 1 poll (sift-down).
//
// ACCEPTANCE: poll order is always descending priority; new top jumps queue.
// DEFENSE Qs: offer/poll O(log n), peek O(1); walk one sift-up on paper.
// SPEC: S7 Heap, S8 priority calc, S11 heap add/remove, Template H heap trace, T10.
public class PriorityDesk {
    private final PriorityQueue<Card> heap = new PriorityQueue<>(
            Comparator.comparingDouble(Card::calculatePriority).reversed());

    public void offer(Card c) { heap.offer(c); }
    public Card peek() { return heap.peek(); }
    public Card poll() { return heap.poll(); }
    public int size() { return heap.size(); }

    public static void main(String[] args) {
        // TODO Dimazana: 5-card script from steps 1-3. Print name + priority each step.
        System.out.println("PriorityDesk. OWNER: Dimazana. (implement 5-card demo)");
    }
}
