package tutorengine.intake;

import java.util.ArrayDeque;
import java.util.Deque;
import tutorengine.model.Card;

// ============================================================================
// OWNER: De Jesus (History & Intake). Karl is NOT in this file.
// Other members: do not edit this file.
// ============================================================================
// WHAT THIS IS: scanner intake FIFO buffer + misread LIFO undo, one ArrayDeque
// used two ways. Cards flow: scan -> stage() -> processNext() -> inventory.
// Mis-scan: undo() puts the last processed card back for correction.
//
// DO THIS (in order):
//  1. stage() = queue.offer(c) - done. processNext() = queue.poll() + push to
//     undo stack - done. undo() = undo.pop() - done. Keep all three.
//  2. Make empty-safe: processNext()/undo() on empty return null (done) - add
//     a printed message in main() demo, not inside the methods.
//  3. Extend main() demo with REAL cards (build 3 Cards inline):
//     stage A, stage B, stage C -> processNext must return A first (FIFO),
//     then undo() must return A (LIFO), then processNext returns B.
//     Print each step so the trace is visible.
//  4. Every processNext() should also call De Jesus's TransactionLog.log().
//  5. TracePacket: 1 page - queue states after each stage/process/undo.
//
// ACCEPTANCE: FIFO order A,B,C; undo returns last processed; empty returns null.
// DEFENSE Qs: Queue vs Stack in one demo; why ArrayDeque O(1) both ends?
// SPEC: S7 Stack/Queue, S11 stack-or-queue op, Template H stack/queue trace.
public class IntakeBuffer {
    private final Deque<Card> queue = new ArrayDeque<>();
    private final Deque<Card> undo = new ArrayDeque<>();

    public void stage(Card c) { queue.offer(c); }
    public Card processNext() {
        Card c = queue.poll();
        if (c != null) undo.push(c);
        return c;
    }
    public Card undo() { return undo.isEmpty() ? null : undo.pop(); }
    public int pending() { return queue.size(); }

    public static void main(String[] args) {
        // TODO De Jesus: build 3 real Cards here and run the FIFO+LIFO script above.
        // Example: new Card("MTG-OTJ-055","Mana Drain","Outlaws of Thunder Junction",
        //   "Blue","Instant",2024,2600.00,1,98,false,"Showcase Display")
        System.out.println("IntakeBuffer. OWNER: De Jesus. pending=0 (implement demo).");
    }
}
