package tutorengine.util;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import tutorengine.model.Card;

// ============================================================================
// OWNER: David (Data & Loader). Karl is NOT in this file.
// Other members: do not edit this file. Open a PR comment if you need changes.
// ============================================================================
// WHAT THIS IS: reads scanner CSV exports into Card objects.
// FILE YOU OWN: Dataset/cards.csv (same folder as this task).
//
// DO THIS (in order):
//  1. Open Dataset/cards.csv. Keep the header row exactly:
//     sku,name,setName,color,cardType,releaseYear,price,quantity,demandScore,isFoil,boxLocationId
//  2. Grow it to 50+ data rows. Real MTG singles from your LGS/shop photos.
//     Example row:
//     MTG-OTJ-056,Lightning Helix,Outlaws of Thunder Junction,Multi,Instant,2024,120.00,6,70,false,Bulk Box B
//  3. Implement load(path) below:
//     a. Files.readAllLines(Path.of(path)); skip line 0 (header) and blank lines.
//     b. Split each line on commas (names are quoted if they contain commas).
//     c. Parse ints/double/boolean; validate: price>=0, quantity>=0, demand 1-100.
//     d. BAD ROW -> print "SKIP line N: <reason>" and continue (never crash).
//     e. new Card(...) per good row; return the list.
//  4. Run the demo: javac tutorengine/model/Card.java tutorengine/util/CSVLoader.java
//     && java tutorengine.util.CSVLoader  -> must print COUNT >= 50.
//  5. Report: fill Template C (field table) + S2 scale + generation rules if scripted.
//
// ACCEPTANCE: load("Dataset/cards.csv").size() >= 50; 1 bad row does not crash.
// DEFENSE Qs: why ArrayList staging (O(1) index for sort/benchmark)?
// SPEC: PROJECT_SPECS.md S6 dataset, S11 load/generate.
public class CSVLoader {
    public static List<Card> load(String path) {
        // TODO David: replace stub below with steps 3a-3e.
        System.out.println("TODO David: parse " + path + " -> List<Card>");
        return new ArrayList<>();
    }

    public static void main(String[] args) {
        // DEMO for presentation: shows count + first 3 cards.
        // TODO David: call load("Dataset/cards.csv") here and print size + 3 samples.
        try {
            List<Card> cards = load("Dataset/cards.csv");
            System.out.println("Loaded " + cards.size() + " cards (need >= 50).");
            System.out.println("OWNER: David.");
            Path p = Path.of("Dataset/cards.csv");
            if (Files.exists(p)) System.out.println("CSV found at Dataset/cards.csv");
            else System.out.println("MISSING Dataset/cards.csv - create it first.");
        } catch (Exception e) {
            System.out.println("ERROR: " + e.getMessage());
        }
    }
}
