package tutorengine.algorithms;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import tutorengine.model.Card;

// ============================================================================
// OWNER: Member 3 (Catalog & Priority). Karl is NOT in this file.
// Other members: do not edit this file.
// ============================================================================
// WHAT THIS IS: the 2 required MANUAL sorts on project objects, ordered by
// Card name (compareToIgnoreCase). BenchmarkSuite calls these; results feed
// Template F + the "small inputs differ from theory" explanation.
//
// DO THIS (in order):
//  1. insertionSort(a): standard loop; compare with c1.compareTo(c2).
//     Reset + count: comparisons++ per compare, movements++ per shift/set.
//  2. selectionSort(a): standard loop with same counting.
//  3. main() demo: build 5 REAL cards SHUFFLED, copy list twice, run each sort,
//     print sorted names + comparisons/movements, then verify both equal
//     new ArrayList<>(shuffled) sorted with Comparator.comparing(Card::getName).
//  4. TracePacket: 1 page - ONE full insertion-sort pass on 5 cards (array state
//     after each insert).
//
// ACCEPTANCE: both outputs identical to List.sort order; counts printed.
// DEFENSE Qs: best/avg/worst of each (Insertion: O(n)/O(n^2)/O(n^2);
//   Selection: O(n^2) always); why n=100 timings can contradict theory.
// SPEC: S8 sorting, S9 sort-vs-sort, Template F.
public class CardSorter {
    public static long comparisons, movements;
    private static final Comparator<Card> BY_NAME =
            (a, b) -> a.getName().compareToIgnoreCase(b.getName());

    public static void insertionSort(List<Card> a) {
        // TODO Member 3: implement; reset comparisons/movements at start.
        comparisons = 0; movements = 0;
        System.out.println("TODO Member 3: manual insertion sort by name");
    }

    public static void selectionSort(List<Card> a) {
        // TODO Member 3: implement; reset comparisons/movements at start.
        comparisons = 0; movements = 0;
        System.out.println("TODO Member 3: manual selection sort by name");
    }

    public static void main(String[] args) {
        // TODO Member 3: 5-card shuffled script from step 3.
        System.out.println("CardSorter. OWNER: Member 3. (implement demo)");
        new ArrayList<Card>().sort(null);
    }
}
