package tutorengine.algorithms;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import tutorengine.model.Card;

// ============================================================================
// OWNER: Huypungco (Graph & Benchmark). Karl is NOT in this file.
// Other members: do not edit this file.
// ============================================================================
// WHAT THIS IS: typo-tolerant SKU lookup. Scanner smudges and mistypes are the
// associate's top error, so when Karl's exact search misses, this suggests the
// nearest VALID SKUs. Node = SKU, edge = 1-character difference.
//
// DO THIS (in order):
//  1. Implement isOneCharDiff(a, b): same length, exactly 1 position differs.
//     ("MTG-OTJ-055" vs "MTG-OTJ-056" -> true; vs "MTG-OTJ-065" -> check.)
//  2. build(cards): one node per SKU; edge every pair with isOneCharDiff.
//     O(n^2 * L) - fine for n=5000. Return adjacency map.
//  3. bfsSuggest(g, typed, maxDepth): start from every node within 1 edit of
//     typed, BFS outward to maxDepth, collect valid SKUs in visit order.
//     No match -> return empty list (caller prints "no suggestions").
//  4. main() demo: 6 SKUs differing by 1 char, query a mistyped SKU
//     (e.g. "MTG-OTJ-05O" with letter O), print suggestions.
//  5. Hook into UI: Karl calls bfsSuggest() on search miss and logs
//     "Not found. Did you mean: ...?" (Karl does the UI half; you own this file.)
//  6. TracePacket: 1 page - BFS levels from the mistyped SKU.
//
// ACCEPTANCE: mistype depth<=2 returns the right SKU; exact SKU needs no suggest.
// DEFENSE Qs: build cost vs BFS O(V+E); what maxDepth=2 guarantees.
// SPEC: S8 BFS application, Template G T05/T07, Template H BFS trace.
// HOW TO TEST (OWNER: Huypungco):
//   RUN:  mvn -q exec:java -Dexec.mainClass=tutorengine.algorithms.SkuCorrector
//   PASS WHEN DONE (6 SKUs that differ by 1 character, e.g. ...-055 / ...-056):
//     - Querying a mistyped SKU like "MTG-OTJ-05O" (letter O) suggests the real
//       "MTG-OTJ-055" / "MTG-OTJ-056" within depth 2.
//     - Querying an exact, correct SKU needs no suggestions (already found).
//     - Querying gibberish ("ZZZ") returns an empty list + message, no crash.
// public class SkuCorrector {
    static boolean isOneCharDiff(String a, String b) {
        // TODO Huypungco: implement (step 1).
        return false;
    }

    public static Map<String, List<String>> build(List<Card> cards) {
        // TODO Huypungco: implement (step 2).
        System.out.println("TODO Huypungco: build 1-char-diff graph over " + cards.size() + " SKUs");
        return new HashMap<>();
    }

    public static List<String> bfsSuggest(Map<String, List<String>> g, String typed, int maxDepth) {
        // TODO Huypungco: implement (step 3). Hint: seed queue with 1-edit neighbors.
        Set<String> seen = new HashSet<>();
        List<String> out = new ArrayList<>();
        Deque<String> q = new ArrayDeque<>();
        System.out.println("TODO Huypungco: BFS suggest for " + typed);
        return out;
    }

    public static void main(String[] args) {
        // TODO Huypungco: demo from step 4.
        System.out.println("SkuCorrector. OWNER: Huypungco. (implement demo)");
    }
}
