package tutorengine.algorithms;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

// ============================================================================
// OWNER: Member 4 (Graph & Benchmark). Karl is NOT in this file.
// Other members: do not edit this file.
// ============================================================================
// WHAT THIS IS: store layout graph. Node = location ("Checkout Counter",
// "Bulk Box C"...), edge = walkable aisle. BFS answers "shortest walk from
// checkout to this card's box"; DFS answers "which zones are reachable at all".
//
// DO THIS (in order):
//  1. Finish bfsPath() with a parent map: queue from start; record
//     parent.get(next)=current; stop at goal; rebuild path goal->start.
//     Missing start/goal or no path -> print message + return empty list.
//  2. dfs() is done (iterative, ArrayDeque as stack). Keep it.
//  3. main() demo: build 10 nodes / 15 edges (spec minimum) in a helper,
//     e.g. Checkout, Intake Desk, Showcase, Bulk A/B/C, Supplies, Back Room,
//     Exit, Grading Table. Print bfsPath(Checkout -> Bulk Box C) and dfs order.
//  4. Wire to search: Karl's SKU hit gives Card.getBoxLocationId() -> call
//     bfsPath("Checkout Counter", boxId) and print "Walk: A -> B -> C".
//  5. TracePacket: 1 page BFS (queue + visited per level) + 1 page DFS.
//  6. Live-change ready: practice "remove one edge and rerun BFS".
//
// ACCEPTANCE: 10 nodes/15 edges; BFS returns min-hop path; DFS visits all.
// DEFENSE Qs: BFS/DFS both O(V+E); queue vs stack; why BFS = shortest hops.
// SPEC: S7 Graph, S8 BFS/DFS, S11 BFS+DFS, Template H traces, T07/T08.
public class StoreNavigator {
    public static Map<String, List<String>> sampleMap() {
        // TODO Member 4: build and return the 10-node/15-edge map. Keep helper
        // separate so bfsPath/dfs stay clean. Undirected: add both directions.
        Map<String, List<String>> g = new HashMap<>();
        return g;
    }

    public static List<String> bfsPath(Map<String, List<String>> g, String start, String goal) {
        // TODO Member 4: implement parent-map BFS (step 1). Stub below.
        System.out.println("TODO Member 4: BFS min-hop " + start + " -> " + goal);
        return new ArrayList<>();
    }

    public static List<String> dfs(Map<String, List<String>> g, String start) {
        Set<String> seen = new HashSet<>();
        List<String> order = new ArrayList<>();
        Deque<String> st = new ArrayDeque<>();
        st.push(start);
        while (!st.isEmpty()) {
            String c = st.pop();
            if (!seen.add(c)) continue;
            order.add(c);
            for (String n : g.getOrDefault(c, List.of())) if (!seen.contains(n)) st.push(n);
        }
        return order;
    }

    public static void main(String[] args) {
        // TODO Member 4: demo from step 3. Print path as "A -> B -> C".
        System.out.println("StoreNavigator. OWNER: Member 4. (implement demo)");
    }
}
