package tutorengine.model;

import java.util.Objects;

// ============================================================================
// OWNER: Huypungco (Graph & Benchmark). Karl is NOT in this file.
// Other members: do not edit this file.
// ============================================================================
// WHAT THIS IS: one vertex of the StoreNavigator graph (a box, shelf, case,
// desk, or counter). Card.boxLocationId points at a StorageLocation id.
//
// DO THIS (in order):
//  1. Add a `zone` field (e.g. "Showcase", "Bulk", "Front") + getter.
//  2. Add equals()/hashCode() by id only (done below as reference - keep).
//  3. main() demo: create the 10 locations Huypungco uses in StoreNavigator
//     and print "id -> label [zone]" lines. Reuse these exact ids as
//     Card.boxLocationId values so search->walk works end to end.
//  4. Report: list the 10 nodes + 15 edges in Template D graph row.
//
// ACCEPTANCE: 10 ids compile in both files; equals() true for same id.
// SPEC: S7 Graph representation.
// HOW TO TEST (OWNER: Huypungco):
//   RUN:  mvn -q exec:java -Dexec.mainClass=tutorengine.model.StorageLocation
//   PASS WHEN DONE:
//     - Prints all 10 locations as "id -> label [zone]", one per line.
//     - Every id printed here also appears as some Card's boxLocationId and as
//       a node in StoreNavigator.sampleMap() (all three lists agree).
//     - Two StorageLocations with the same id compare equal (== via equals()).
public class StorageLocation {
    private final String id;
    private final String label;
    // TODO Huypungco: add zone field + getter (step 1).

    public StorageLocation(String id, String label) { this.id = id; this.label = label; }
    public String getId() { return id; }
    public String getLabel() { return label; }

    @Override public boolean equals(Object o) {
        return o instanceof StorageLocation s && Objects.equals(id, s.id);
    }
    @Override public int hashCode() { return Objects.hashCode(id); }

    public static void main(String[] args) {
        // TODO Huypungco: print the 10 locations (step 3).
        System.out.println(new StorageLocation("BOX-GREEN-03", "Bulk Box C").getLabel());
        System.out.println("StorageLocation. OWNER: Huypungco.");
    }
}
