package tutorengine.model;

import java.util.LinkedList;
import java.util.List;

// ============================================================================
// OWNER: De Jesus (History & Intake). Karl is NOT in this file.
// Other members: do not edit this file.
// ============================================================================
// WHAT THIS IS: sequential intake/change log (LinkedList). Every scan/add/
// delete in the app appends one line here. Proves Linked List use.
//
// DO THIS (in order):
//  1. Keep entries as LinkedList<String> (already done). Entry format:
//     "INTAKE <SKU> x<qty>"  e.g. "INTAKE MTG-OTJ-055 x1"
//     "DELETE <SKU>" / "UNDO <entry>"
//  2. log() appends to tail (addLast = O(1)) - done. Keep it.
//  3. undoLast() removes tail - done. Return null + print a message when empty.
//  4. Add printAll(): loop entries in order, number them "1. ...", "2. ...".
//  5. Extend main() demo: log 3 real SKUs, printAll, undoLast, printAll again.
//     Must show: normal case + empty-log case (call undoLast on empty).
//  6. TracePacket: 1 page - insert 3 entries step by step (head/tail pointers),
//     then 1 delete. Use real SKUs.
//
// ACCEPTANCE: 3 logs print in order; undo removes last; empty undo is safe.
// DEFENSE Qs: why LinkedList not ArrayList (O(1) head/tail, no shifting)?
// SPEC: S7 Linked List, S11 list traversal, Template H list trace, T01-T03.
// HOW TO TEST (OWNER: De Jesus):
//   RUN:  mvn -q exec:java -Dexec.mainClass=tutorengine.model.TransactionLog
//   PASS WHEN DONE:
//     - 3 logged entries print in the order they were added, numbered 1, 2, 3.
//     - undoLast() removes and returns entry 3; printing again shows only 1, 2.
//     - Calling undoLast() on an empty log prints a friendly message and
//       returns null instead of throwing.
public class TransactionLog {
    private final LinkedList<String> entries = new LinkedList<>();

    public void log(String entry) { entries.addLast(entry); }
    public String undoLast() { return entries.isEmpty() ? null : entries.removeLast(); }
    public List<String> all() { return entries; }

    // TODO De Jesus: implement printAll() here (numbered traversal).

    public static void main(String[] args) {
        // TODO De Jesus: extend this demo to 3 entries + undo + empty-case.
        TransactionLog t = new TransactionLog();
        t.log("INTAKE MTG-OTJ-055 x1");
        System.out.println(t.all());
        System.out.println("TransactionLog. OWNER: De Jesus.");
    }
}
